version: 2
jobs:
  build:
    working_directory: ~/axios-adapter
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: axios-adapter-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: axios-adapter-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test
      - run: npm run upload:coverage
